### ISSUE TITLE
Figshare ImportError python

### ISSUE THREAD

**Issue by jjtukker** [RoyVII/cnn-ripple#2]
hi Rodrigo,
still trying to get cnn-ripple to work, and ran into another issue that again may not be directly related to cnn-ripple, but I hope you can have another look.
The issue is with figshare. I was trying to use this as you suggested in the example notebook, but just running this from a terminal, and got some errors I could not deal with (I am a novice to Python): 

>>> sys.path.insert(1,'./src/cnn')
>>> sys.path.insert(1,'./figshare')
>>> from figshare import Figshare
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Figshare' from 'figshare' (/Users/user-adm/Lab/Scripts/Python/cnn-ripple/figshare/__init__.py)
>>> from figshare import figshare
>>> fshare=figshare()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
>>> os.getcwd()
'/Users/user-adm/Lab/Scripts/Python/cnn-ripple'
>>> os.chdir("figshare")
>>> os.getcwd()
'/Users/user-adm/Lab/Scripts/Python/cnn-ripple/figshare'
>>> fshare=figshare()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
>>> from figshare import Figshare
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Figshare' from 'figshare' (/Users/user-adm/Lab/Scripts/Python/cnn-ripple/figshare/__init__.py)
>>> os.listdir()
['LICENSE.md', 'figshare.py', '__init__.py', '__pycache__', 'README.md']

This is on MacOS 12.2.1, running python from a z-shell.
thanks,
John

**Comment by RoyVII** [comment]
Hi John!

Since you are running your shell from the `cnn-ripple` root directory it should work if you do
```
from figshare.figshare import Figshare  # from file figshare in folder figshare import Figshare
```

If this was indeed the problem then it was caused by how Python looks for its modules. `sys.path` contains a list with directories where it looks for modules, in order. The first element is the current directory and with `sys.path.insert(1,'./figshare')` we insert the `figshare` folder in second position.

```
[ '',
 './figshare',
'/home/miniconda3/envs/tfenv/lib/python3.7']
```

Because of this, when executing from the `cnn-ripple` dir, it first looks in that folder, finds the directory called `figshare`  and tries to load a file named `Figshare.py`, which does not exist. It never gets to check the path that we inserted. We should do `sys.path.insert(0,'./figshare')` to make that happen.

Best,

Rodrigo
